version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 1972
      - 55008:52773
      - 53773
    volumes:
      - ./:/irisrun/repo
      - ./src/csp:/home/irisowner/irisbuild/src/csp
      